### ISSUE TITLE
Freemind: The requested URL returned error: 404 Not Found (exit code 22)

### ISSUE THREAD

**Issue by tcinbis** [autopkg/prochat-recipes#3]
Hello,
today the following error occurred:
 
`The following recipes failed:
    com.github.prochat.download.freemind
        Error in com.github.prochat.download.freemind: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)`

**Comment by neilmartin83** [comment]
Bump - we are seeing the same issue. Looks like the URL for the hosted DMG has changed. https://www.mirrorservice.org/sites/ftp.sourceforge.net/pub/sourceforge/f/fr/freemind/freemind/1.0.1/FreeMind_1.0.1.dmg results in the following: 
![image](https://user-images.githubusercontent.com/10920581/94928131-1e60fc00-04bb-11eb-8c2e-119148c7190b.png)

**Comment by Daz-wallace** [comment]
Bump 😊

**Comment by neilmartin83** [comment]
Bump :D

**Comment by Daz-wallace** [comment]
Bumpy McBumpFace 😊

**Comment by neilmartin83** [comment]
Every elephant as he grows,
Learns to keep on his toes
In his element as he goes,
Bump Bump Bumpety Bump... BUMP

**Comment by neilmartin83** [comment]
![image](https://user-images.githubusercontent.com/10920581/98258996-71761500-1f79-11eb-8161-2573b0535e94.png)

**Comment by neilmartin83** [comment]
Bump :)

**Comment by Daz-wallace** [comment]
@prochat Are you able to review?

Or would you rather we take over the Freemind recipes?

Thanks

**Comment by neilmartin83** [comment]
Bump.

**Comment by neilmartin83** [comment]
Bump

**Comment by neilmartin83** [comment]
![image](https://user-images.githubusercontent.com/10920581/101917210-e44d5e00-3bbf-11eb-9163-3c4ad43866cb.png)

**Comment by tcinbis** [comment]
I'm starting to hope that this PR never gets merged by @prochat , so that I can continue to see awesome ways to bump a PR by you @neilmartin83 😂

**Comment by neilmartin83** [comment]
Thanks @tcinbis - @Daz-wallace or myself will be back in about a week after we receive the next recipe failure alert. We've been trying to seek out @prochat in the MacAdmins Slack and by other means in case they're not aware of the goings on here. No joy so far. 😞

**Comment by tcinbis** [comment]
I'm sorry to hear that @neilmartin83 ! Judging from the commit history it seems questionable whether this repo is still maintained at all.

Maybe it would make sense to add some new maintainers to this repository to be able to provide continued support and fixes (since this is somewhat a core repo under the autopkg umbrella).

Unfortunately, it has been a while since I actively participated in the autopkg community so I am not sure who to ping here.

**Comment by neilmartin83** [comment]
![image](https://user-images.githubusercontent.com/10920581/102093634-494fc080-3e19-11eb-99a1-d7ec409e680f.png)

**Comment by neilmartin83** [comment]
Bump

**Comment by neilmartin83** [comment]
Bump - have asked the AutoPkg owners to merge the PRs that fix this in #autopkg on the MacAdmins Slack.

**Comment by neilmartin83** [comment]
Created new recipes at https://github.com/autopkg/dataJAR-recipes/tree/master/FreeMind and submitted PR #12 to delete the broken recipes from this repo.
